### ISSUE TITLE
javascript web3 instance that spits out eth gas station metrics

### ISSUE THREAD

**Issue by owocki** [gitcoinco/skunkworks#1]
Requirements
* npm-installable (or can be loaded in a browser)
* feed a web3 instance in 
* it outputs a prediction table similar to https://ethgasstation.info/predictionTable.php , but in json

**Comment by owocki** [comment]
reference implmentations in python:
https://github.com/ethereum/web3.py/issues/496
https://github.com/ethgasstation/ethgasstation-adaptive-oracle

**Comment by owocki** [comment]
metamask says: We need this if we can run it of the rpc without killing infura

**Comment by owocki** [comment]
according to Daniel Ternyak this isnt possible in browser bc "You’ll need to make requests anyway to get block data, and at that point you may as well have the server handle everything and just expose a simple REST/GraphQL/whatever you like HTTP JSON service"

**Comment by monokh** [comment]
The reference implementation seems very coupled with the use case for ethgasstation and makes too much network calls to be suitable for metamask or other backend-less apps. In those cases a simpler approach might suffice, maybe the min/average/max of the last few blocks? Perhaps this can be an option in the javascript version? 
I also recall a eth gas station endpoint that gave safe/average/fast gas prices? Probably very close to what metamask or other wallets would want.

**Comment by owocki** [comment]
@monokh https://ethgasstation.info/json/ethgasAPI.json might be what you were looking for

**Comment by JasoonS** [comment]
Hi, I'll take a look at this. So the idea is to create a purely backend tool for node apps say?

https://github.com/ethgasstation/ethgasstation-adaptive-oracle also makes use of the `txpool` to make more accurate predictions, txpool isn't available in web3js, so accessing that will also have to be built in.

I'm curious what you mean by feed a web3 instance, could you elaborate?

Possibilities I can think of:
```
web3 = web3-gas-price-predictor(web3)
const gasPricePredictions = web3.getGasPricePredictions()
```
or
```
// where `gasPredictor` doesn't have the rest of web3's functionality
const gasPredictor = web3-gas-price-predictor(web3)
const gasPricePredictions = gasPredictor.getPredictions()
```
or even
```
// where `gasPredictor` doesn't have the rest of web3's functionality
const getGasPricePredictions = requre('web3-gas-price-predictor').getGasPricePredictions
const gasPricePredictions = getGasPricePredictions(web3)
```

**Comment by owocki** [comment]
i think any of those code examples could work as interfaces.

i wonder if the recent progress that ethgasstation has made in this area means that the gitcoin community doesnt need to sponsor this https://twitter.com/ETHGasStation/status/945650844648828928

**Comment by JasoonS** [comment]
Ah, sure thing, that is a neat development!
