### ISSUE TITLE
Wallet Connect for gitcoin.co/requestmoney not loading 

### ISSUE THREAD

**Issue by ufkhan97** [gitcoinco/skunkworks#254]
Hi,

After trying to claim my bounty from completing a gitcoin grants data analysis(https://github.com/gitcoinco/skunkworks/issues/252#issuecomment-1004443434). I could not proceed through the steps of gitcoin.co/requestmoney

I opened gitcoin on my Mac, already signed into gitcoin. I scan the Wallet Connect QR code (using Trust Wallet on my phone) and it connects on my mobile but nothing happens on my web browser. It stays stuck on the QR code display. I think it should proceed to ask me to sign a transaction but nothing happens. Please let me know if I'm doing something wrong

Thanks,

Umar

**Comment by csggene3** [comment]
Were you ever able to claim this bounty @ufkhan97 ?

**Comment by ufkhan97** [comment]
Hi @csggene3 Thank you for the comment and offer of help! I did not have this issue resolved and just tried the website again. I would definitely appreciate any help posting this issue in the correct repo. Thank you!

**Comment by ufkhan97** [comment]
I was able to connect and submit a request by using Desktop Chrome + Metamask
