### ISSUE TITLE
figure out daily coding challenge spec

### ISSUE THREAD

**Issue by owocki** [gitcoinco/skunkworks#56]
a daily coding challenge module or email that allows folks to stay engaged and learn solidity over time

do we need 'tracks'?  ie solidity track, Ethereum basics track, etc..

**Comment by eswarasai** [comment]
@owocki -- Should this be an app where we provide new challenges daily for users to participate or will we be curating an email with challenge on daily basis?

**Comment by owocki** [comment]
i haven't spent much time specifying this.. but i think there are valid reasons to pursue both of those avenues.

why do you ask?

**Comment by eswarasai** [comment]
@owocki -- I really liked this idea and would like to contribute for this, at the same time leverage the knowledge of Solidity while working on the challenges 😄

**Comment by owocki** [comment]
@eswarasai want to take a stab at defining a spec for an MVP?  curious what direction youd take this

**Comment by PixelantDesign** [comment]
A series of emails could be an easy way to get started. Maybe like a ‘Solidity Basics Series’ , ‘ Solidity in Eight Weeks’ or something along those lines. Maybe there are lesson plans that can be leveraged from another platform. For help, users could go to a dedicated slack channel. This ties nicely into mentoring.

**Comment by eswarasai** [comment]
@owocki -- Although I'd agree with the idea suggested by @PixelantDesign, I'm also thinking along the lines of engaging the users with coding challenges rather than just sending out the emails with the lessons which might just end up lying in the inboxes.

So there are multiple ideas I can think about right now. I'm listing a few below :
1. Like Alisa suggested, ` Solidity in Eight Weeks` is along the lines of helping users with how to get started with Solidity
2. Weekly coding challenge where users will submit the challenge solutions on the platform. We can have judges who'd evaluate the solutions and rank them in the order based on few factors like how quickly a user solved this challenge, is it a best possible solution etc. I'd recommend to incentivise this to keep the momentum on the platform
3. Mentorship -- Not really sure how we can fit this in the above 2 ideas but I do really like the users to be able to connect with other Solidity developers and discuss related things or even stay up-to-date with the trends etc

PS : If we can generalise the above platform to support not just for Solidity and for each and every field like UI/UX, Frontend, Backend etc. it might be even better.

**Comment by tra38** [comment]
>i wonder if theres any open source software we can leverage so that we're just focused on the content here and not trying to boil the ocean by reinventing the proverbial ( educational ) wheel here

freecodecamp.org is [open-source](https://github.com/freeCodeCamp/freeCodeCamp). Maybe we can use it as a starting point?

**Comment by PixelantDesign** [comment]
All depens who we are trying to help. The people that are on the fast track will likely research and try to learn it right away ( or may already have the funamentals down). 

+1 on leveraging resources that exist.

**Comment by owocki** [comment]
> freecodecamp.org is open-source, where challenges are stored in JSON files. Maybe we can use it as a starting point?

seems like a good starting point to me.

**Comment by eswarasai** [comment]
> I wonder what the incentive would be for the judges.. And who should pay the incentives?

I was actually referring to incentivise for the winners of the challenges, hoping that judges can be of Gitcoin platform, helping the participants to learn about the best possible solutions for the various challenges. We can incentivise it both the ways, but not exactly sure what should be these incentives and who should be paying them. Having a sponsor or participating fee for a challenge, something around these lines maybe?

@tra38 -- That's a pretty solid open-source project out there 👍 

@owocki -- If we can come up with a plan on how to get started and what all features can be divided into phases, we can get this thing going 😄

**Comment by owocki** [comment]
seems to me it'd be more efficient to procedurally grade all of the challenges.. too complex to have judges for every submission.

**Comment by eswarasai** [comment]
@owocki -- I agree. For starters, we can ignore judges evaluating the challenges as well as incentivising them. Can you help us with locking the Phase 1 requirements of the product, so that we can get started with the development for this and update it down the line?

**Comment by owocki** [comment]
> Can you help us with locking the Phase 1 requirements of the product, so that we can get started with the development for this and update it down the line?

Sure, do you want to take a first stab and writing up the requirements or should I?

**Comment by eswarasai** [comment]
@owocki -- I feel you might be the better person to come up with the requirements. So I'd really like you to help us all out here 😄

**Comment by owocki** [comment]
OK, here is what I think for an MVP.  Directionally, I *really* like the way that free code camp organizes their project and I think we should plan to 

1. Create a branded install of FreeCodeCamp at codecamp.gitcoin.co
1. Create web3 basic concepts track.
1. Create Metamask track.
1. Create Solidity beginner track.

When each lesson is completed, I think the system should be interoperable with Gitcoin, and the user should receive a badge on their github profile denoting that they've completed each track.  

@eswarasai @PixelantDesign does this seem directionally correct?  If so, I will write up a full specification.

**Comment by PixelantDesign** [comment]
I like. Sounds good to me!

**Comment by eswarasai** [comment]
@owocki -- I like where we're going with this. Please do let us know once we have a full spec in place

**Comment by owocki** [comment]
Here you go @eswarasai https://github.com/gitcoinco/web/issues/631

**Comment by owocki** [comment]
@eswarasai are you interested in working on https://github.com/gitcoinco/web/issues/631 ? im trying to figureo ut the bounty amount to post for it
